#!/usr/bin/env python

# AUTO GENERATED FILE - PLEASE CHECK gen.py! #

Instructions = [{'code': 0,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '00',
  'instruction': 'NOP',
  'name': 'NOP',
  'templateData': {'args': [''], 'name': 'NOP'}},
 {'code': 1,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '01',
  'instruction': 'LD BC,d16',
  'name': 'LDBCnn',
  'templateData': {'args': ['B', 'C'], 'name': 'LD__nn'}},
 {'code': 2,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '02',
  'instruction': 'LD [BC],A',
  'name': 'LDBCmA',
  'templateData': {'args': ['B', 'C', 'A'], 'name': 'LD__m_'}},
 {'code': 3,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '03',
  'instruction': 'INC BC',
  'name': 'INCBC',
  'templateData': {'args': ['B', 'C'], 'name': 'INC'}},
 {'code': 4,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '04',
  'instruction': 'INC B',
  'name': 'INCr_b',
  'templateData': {'args': ['B'], 'name': 'INCr'}},
 {'code': 5,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '05',
  'instruction': 'DEC B',
  'name': 'DECr_b',
  'templateData': {'args': ['B'], 'name': 'DECr'}},
 {'code': 6,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '06',
  'instruction': 'LD B, d8',
  'name': 'LDrn_b',
  'templateData': {'args': ['B'], 'name': 'LDrn_'}},
 {'code': 7,
  'cycles': 4,
  'flagResult': {'carry': None,
                 'halfcarry': False,
                 'sub': False,
                 'zero': False},
  'hexCode': '07',
  'instruction': 'RLCA',
  'name': 'RLCA',
  'templateData': {'args': [''], 'name': 'RLCA'}},
 {'code': 8,
  'cycles': 20,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '08',
  'instruction': 'LD [a16], SP',
  'name': 'LDmmSP',
  'templateData': {'args': [''], 'name': 'LDmmSP'}},
 {'code': 9,
  'cycles': 8,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': None},
  'hexCode': '09',
  'instruction': 'ADD HL,BC',
  'name': 'ADDHLBC',
  'templateData': {'args': ['B', 'C'], 'name': 'ADDHL'}},
 {'code': 10,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '0A',
  'instruction': 'LD A, [BC]',
  'name': 'LDABCm',
  'templateData': {'args': ['A', 'B', 'C'], 'name': 'LD___m'}},
 {'code': 11,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '0B',
  'instruction': 'DEC BC',
  'name': 'DECBC',
  'templateData': {'args': ['B', 'C'], 'name': 'DEC'}},
 {'code': 12,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '0C',
  'instruction': 'INC C',
  'name': 'INCr_c',
  'templateData': {'args': ['C'], 'name': 'INCr'}},
 {'code': 13,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '0D',
  'instruction': 'DEC C',
  'name': 'DECr_c',
  'templateData': {'args': ['C'], 'name': 'DECr'}},
 {'code': 14,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '0E',
  'instruction': 'LD C, d8',
  'name': 'LDrn_c',
  'templateData': {'args': ['C'], 'name': 'LDrn_'}},
 {'code': 15,
  'cycles': 4,
  'flagResult': {'carry': None,
                 'halfcarry': False,
                 'sub': False,
                 'zero': False},
  'hexCode': '0F',
  'instruction': 'RRCA',
  'name': 'RRCA',
  'templateData': {'args': [''], 'name': 'RRCA'}},
 {'code': 16,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '10',
  'instruction': 'STOP',
  'name': 'STOP',
  'templateData': {'args': [''], 'name': 'DJNZn'}},
 {'code': 17,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '11',
  'instruction': 'LD DE, d16',
  'name': 'LDDEnn',
  'templateData': {'args': ['D', 'E'], 'name': 'LD__nn'}},
 {'code': 18,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '12',
  'instruction': 'LD [DE], A',
  'name': 'LDDEmA',
  'templateData': {'args': ['D', 'E', 'A'], 'name': 'LD__m_'}},
 {'code': 19,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '13',
  'instruction': 'INC DE',
  'name': 'INCDE',
  'templateData': {'args': ['D', 'E'], 'name': 'INC'}},
 {'code': 20,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '14',
  'instruction': 'INC D',
  'name': 'INCr_d',
  'templateData': {'args': ['D'], 'name': 'INCr'}},
 {'code': 21,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '15',
  'instruction': 'DEC D',
  'name': 'DECr_d',
  'templateData': {'args': ['D'], 'name': 'DECr'}},
 {'code': 22,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '16',
  'instruction': 'LD D, d8',
  'name': 'LDrn_d',
  'templateData': {'args': ['D'], 'name': 'LDrn_'}},
 {'code': 23,
  'cycles': 4,
  'flagResult': {'carry': None,
                 'halfcarry': False,
                 'sub': False,
                 'zero': False},
  'hexCode': '17',
  'instruction': 'RLA',
  'name': 'RLA',
  'templateData': {'args': [''], 'name': 'RLA'}},
 {'code': 24,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '18',
  'instruction': 'JR r8',
  'name': 'JRn',
  'templateData': {'args': [''], 'name': 'JRn'}},
 {'code': 25,
  'cycles': 8,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': None},
  'hexCode': '19',
  'instruction': 'ADD HL, DE',
  'name': 'ADDHLDE',
  'templateData': {'args': ['D', 'E'], 'name': 'ADDHL'}},
 {'code': 26,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '1A',
  'instruction': 'LD A, [DE]',
  'name': 'LDADEm',
  'templateData': {'args': ['A', 'D', 'E'], 'name': 'LD___m'}},
 {'code': 27,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '1B',
  'instruction': 'DEC DE',
  'name': 'DECDE',
  'templateData': {'args': ['D', 'E'], 'name': 'DEC'}},
 {'code': 28,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '1C',
  'instruction': 'INC E',
  'name': 'INCr_e',
  'templateData': {'args': ['E'], 'name': 'INCr'}},
 {'code': 29,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '1D',
  'instruction': 'DEC E',
  'name': 'DECr_e',
  'templateData': {'args': ['E'], 'name': 'DECr'}},
 {'code': 30,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '1E',
  'instruction': 'LD E, d8',
  'name': 'LDrn_e',
  'templateData': {'args': ['E'], 'name': 'LDrn_'}},
 {'code': 31,
  'cycles': 4,
  'flagResult': {'carry': None,
                 'halfcarry': False,
                 'sub': False,
                 'zero': False},
  'hexCode': '1F',
  'instruction': 'RRA',
  'name': 'RRA',
  'templateData': {'args': [''], 'name': 'RRA'}},
 {'code': 32,
  'cycles': [12, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '20',
  'instruction': 'JR NZ, r8',
  'name': 'JRNZn',
  'templateData': {'args': [''], 'name': 'JRNZn'}},
 {'code': 33,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '21',
  'instruction': 'LD HL, d16',
  'name': 'LDHLnn',
  'templateData': {'args': ['H', 'L'], 'name': 'LD__nn'}},
 {'code': 34,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '22',
  'instruction': 'LD [HL+], A',
  'name': 'LDHLIA',
  'templateData': {'args': [''], 'name': 'LDHLIA'}},
 {'code': 35,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '23',
  'instruction': 'INC HL',
  'name': 'INCHL',
  'templateData': {'args': [''], 'name': 'INCHL'}},
 {'code': 36,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '24',
  'instruction': 'INC H',
  'name': 'INCr_h',
  'templateData': {'args': ['H'], 'name': 'INCr'}},
 {'code': 37,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '25',
  'instruction': 'DEC H',
  'name': 'DECr_h',
  'templateData': {'args': ['H'], 'name': 'DECr'}},
 {'code': 38,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '26',
  'instruction': 'LD H,d8',
  'name': 'LDrn_h',
  'templateData': {'args': ['H'], 'name': 'LDrn_'}},
 {'code': 39,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': False, 'sub': None, 'zero': 'Z'},
  'hexCode': '27',
  'instruction': 'DAA',
  'name': 'DAA',
  'templateData': {'args': [''], 'name': 'DAA'}},
 {'code': 40,
  'cycles': [12, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '28',
  'instruction': 'JR Z,r8',
  'name': 'JRZn',
  'templateData': {'args': [''], 'name': 'JRZn'}},
 {'code': 41,
  'cycles': 8,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': None},
  'hexCode': '29',
  'instruction': 'ADD HL, HL',
  'name': 'ADDHLHL',
  'templateData': {'args': ['H', 'L'], 'name': 'ADDHL'}},
 {'code': 42,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '2A',
  'instruction': 'LD A, [HL+]',
  'name': 'LDAHLI',
  'templateData': {'args': [''], 'name': 'LDAHLI'}},
 {'code': 43,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '2B',
  'instruction': 'DEC HL',
  'name': 'DECHL',
  'templateData': {'args': [''], 'name': 'DECHL'}},
 {'code': 44,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '2C',
  'instruction': 'INC L',
  'name': 'INCr_l',
  'templateData': {'args': ['L'], 'name': 'INCr'}},
 {'code': 45,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '2D',
  'instruction': 'DEC L',
  'name': 'DECr_l',
  'templateData': {'args': ['L'], 'name': 'DECr'}},
 {'code': 46,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '2E',
  'instruction': 'LD L, d8',
  'name': 'LDrn_l',
  'templateData': {'args': ['L'], 'name': 'LDrn_'}},
 {'code': 47,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': True, 'zero': None},
  'hexCode': '2F',
  'instruction': 'CPL',
  'name': 'CPL',
  'templateData': {'args': [''], 'name': 'CPL'}},
 {'code': 48,
  'cycles': [12, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '30',
  'instruction': 'JR NC, r8',
  'name': 'JRNCn',
  'templateData': {'args': [''], 'name': 'JRNCn'}},
 {'code': 49,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '31',
  'instruction': 'LD SP, d16',
  'name': 'LDSPnn',
  'templateData': {'args': [''], 'name': 'LDSPnn'}},
 {'code': 50,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '32',
  'instruction': 'LD [HL-], A',
  'name': 'LDHLDA',
  'templateData': {'args': [''], 'name': 'LDHLDA'}},
 {'code': 51,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '33',
  'instruction': 'INC SP',
  'name': 'INCSP',
  'templateData': {'args': [''], 'name': 'INCSP'}},
 {'code': 52,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '34',
  'instruction': 'INC [HL]',
  'name': 'INCHLm',
  'templateData': {'args': [''], 'name': 'INCHLm'}},
 {'code': 53,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '35',
  'instruction': 'DEC [HL]',
  'name': 'DECHLm',
  'templateData': {'args': [''], 'name': 'DECHLm'}},
 {'code': 54,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '36',
  'instruction': 'LD [HL], d8',
  'name': 'LDHLmn',
  'templateData': {'args': [''], 'name': 'LDHLmn'}},
 {'code': 55,
  'cycles': 4,
  'flagResult': {'carry': True,
                 'halfcarry': False,
                 'sub': False,
                 'zero': None},
  'hexCode': '37',
  'instruction': 'SCF',
  'name': 'SCF',
  'templateData': {'args': [''], 'name': 'SCF'}},
 {'code': 56,
  'cycles': [12, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '38',
  'instruction': 'JR C, r8',
  'name': 'JRCn',
  'templateData': {'args': [''], 'name': 'JRCn'}},
 {'code': 57,
  'cycles': 8,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': None},
  'hexCode': '39',
  'instruction': 'ADD HL, SP',
  'name': 'ADDHLSP',
  'templateData': {'args': [''], 'name': 'ADDHLSP'}},
 {'code': 58,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '3A',
  'instruction': 'LD A,[HL-]',
  'name': 'LDAHLD',
  'templateData': {'args': [''], 'name': 'LDAHLD'}},
 {'code': 59,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '3B',
  'instruction': 'DEC SP',
  'name': 'DECSP',
  'templateData': {'args': [''], 'name': 'DECSP'}},
 {'code': 60,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '3C',
  'instruction': 'INC A',
  'name': 'INCr_a',
  'templateData': {'args': ['A'], 'name': 'INCr'}},
 {'code': 61,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '3D',
  'instruction': 'DEC A',
  'name': 'DECr_a',
  'templateData': {'args': ['A'], 'name': 'DECr'}},
 {'code': 62,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '3E',
  'instruction': 'LD A,d8',
  'name': 'LDrn_a',
  'templateData': {'args': ['A'], 'name': 'LDrn_'}},
 {'code': 63,
  'cycles': 4,
  'flagResult': {'carry': None,
                 'halfcarry': False,
                 'sub': False,
                 'zero': None},
  'hexCode': '3F',
  'instruction': 'CCF',
  'name': 'CCF',
  'templateData': {'args': [''], 'name': 'CCF'}},
 {'code': 64,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '40',
  'instruction': 'LD B, B',
  'name': 'LDrr_bb',
  'templateData': {'args': ['B', 'B'], 'name': 'LDrr'}},
 {'code': 65,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '41',
  'instruction': 'LD B, C',
  'name': 'LDrr_bc',
  'templateData': {'args': ['B', 'C'], 'name': 'LDrr'}},
 {'code': 66,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '42',
  'instruction': 'LD B, D',
  'name': 'LDrr_bd',
  'templateData': {'args': ['B', 'D'], 'name': 'LDrr'}},
 {'code': 67,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '43',
  'instruction': 'LD B, E',
  'name': 'LDrr_be',
  'templateData': {'args': ['B', 'E'], 'name': 'LDrr'}},
 {'code': 68,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '44',
  'instruction': 'LD B, H',
  'name': 'LDrr_bh',
  'templateData': {'args': ['B', 'H'], 'name': 'LDrr'}},
 {'code': 69,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '45',
  'instruction': 'LD B, L',
  'name': 'LDrr_bl',
  'templateData': {'args': ['B', 'L'], 'name': 'LDrr'}},
 {'code': 70,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '46',
  'instruction': 'LD B, [HL]',
  'name': 'LDrHLm_b',
  'templateData': {'args': ['B'], 'name': 'LDrHLm_'}},
 {'code': 71,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '47',
  'instruction': 'LD B, A',
  'name': 'LDrr_ba',
  'templateData': {'args': ['B', 'A'], 'name': 'LDrr'}},
 {'code': 72,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '48',
  'instruction': 'LD C, B',
  'name': 'LDrr_cb',
  'templateData': {'args': ['C', 'B'], 'name': 'LDrr'}},
 {'code': 73,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '49',
  'instruction': 'LD C, C',
  'name': 'LDrr_cc',
  'templateData': {'args': ['C', 'C'], 'name': 'LDrr'}},
 {'code': 74,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4A',
  'instruction': 'LD C, D',
  'name': 'LDrr_cd',
  'templateData': {'args': ['C', 'D'], 'name': 'LDrr'}},
 {'code': 75,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4B',
  'instruction': 'LD C, E',
  'name': 'LDrr_ce',
  'templateData': {'args': ['C', 'E'], 'name': 'LDrr'}},
 {'code': 76,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4C',
  'instruction': 'LD C, H',
  'name': 'LDrr_ch',
  'templateData': {'args': ['C', 'H'], 'name': 'LDrr'}},
 {'code': 77,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4D',
  'instruction': 'LD C, L',
  'name': 'LDrr_cl',
  'templateData': {'args': ['C', 'L'], 'name': 'LDrr'}},
 {'code': 78,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4E',
  'instruction': 'LD C, [HL]',
  'name': 'LDrHLm_c',
  'templateData': {'args': ['C'], 'name': 'LDrHLm_'}},
 {'code': 79,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '4F',
  'instruction': 'LD C, A',
  'name': 'LDrr_ca',
  'templateData': {'args': ['C', 'A'], 'name': 'LDrr'}},
 {'code': 80,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '50',
  'instruction': 'LD D, B',
  'name': 'LDrr_db',
  'templateData': {'args': ['D', 'B'], 'name': 'LDrr'}},
 {'code': 81,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '51',
  'instruction': 'LD D, C',
  'name': 'LDrr_dc',
  'templateData': {'args': ['D', 'C'], 'name': 'LDrr'}},
 {'code': 82,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '52',
  'instruction': 'LD D, D',
  'name': 'LDrr_dd',
  'templateData': {'args': ['D', 'D'], 'name': 'LDrr'}},
 {'code': 83,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '53',
  'instruction': 'LD D, E',
  'name': 'LDrr_de',
  'templateData': {'args': ['D', 'E'], 'name': 'LDrr'}},
 {'code': 84,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '54',
  'instruction': 'LD D, H',
  'name': 'LDrr_dh',
  'templateData': {'args': ['D', 'H'], 'name': 'LDrr'}},
 {'code': 85,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '55',
  'instruction': 'LD D, L',
  'name': 'LDrr_dl',
  'templateData': {'args': ['D', 'L'], 'name': 'LDrr'}},
 {'code': 86,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '56',
  'instruction': 'LD D, [HL]',
  'name': 'LDrHLm_d',
  'templateData': {'args': ['D'], 'name': 'LDrHLm_'}},
 {'code': 87,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '57',
  'instruction': 'LD D, A',
  'name': 'LDrr_da',
  'templateData': {'args': ['D', 'A'], 'name': 'LDrr'}},
 {'code': 88,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '58',
  'instruction': 'LD E, B',
  'name': 'LDrr_eb',
  'templateData': {'args': ['E', 'B'], 'name': 'LDrr'}},
 {'code': 89,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '59',
  'instruction': 'LD E, C',
  'name': 'LDrr_ec',
  'templateData': {'args': ['E', 'C'], 'name': 'LDrr'}},
 {'code': 90,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5A',
  'instruction': 'LD E, D',
  'name': 'LDrr_ed',
  'templateData': {'args': ['E', 'D'], 'name': 'LDrr'}},
 {'code': 91,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5B',
  'instruction': 'LD E, E',
  'name': 'LDrr_ee',
  'templateData': {'args': ['E', 'E'], 'name': 'LDrr'}},
 {'code': 92,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5C',
  'instruction': 'LD E, H',
  'name': 'LDrr_eh',
  'templateData': {'args': ['E', 'H'], 'name': 'LDrr'}},
 {'code': 93,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5D',
  'instruction': 'LD E, L',
  'name': 'LDrr_el',
  'templateData': {'args': ['E', 'L'], 'name': 'LDrr'}},
 {'code': 94,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5E',
  'instruction': 'LD E, [HL]',
  'name': 'LDrHLm_e',
  'templateData': {'args': ['E'], 'name': 'LDrHLm_'}},
 {'code': 95,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '5F',
  'instruction': 'LD E, A',
  'name': 'LDrr_ea',
  'templateData': {'args': ['E', 'A'], 'name': 'LDrr'}},
 {'code': 96,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '60',
  'instruction': 'LD H, B',
  'name': 'LDrr_hb',
  'templateData': {'args': ['H', 'B'], 'name': 'LDrr'}},
 {'code': 97,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '61',
  'instruction': 'LD H, C',
  'name': 'LDrr_hc',
  'templateData': {'args': ['H', 'C'], 'name': 'LDrr'}},
 {'code': 98,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '62',
  'instruction': 'LD H, D',
  'name': 'LDrr_hd',
  'templateData': {'args': ['H', 'D'], 'name': 'LDrr'}},
 {'code': 99,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '63',
  'instruction': 'LD H, E',
  'name': 'LDrr_he',
  'templateData': {'args': ['H', 'E'], 'name': 'LDrr'}},
 {'code': 100,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '64',
  'instruction': 'LD H, H',
  'name': 'LDrr_hh',
  'templateData': {'args': ['H', 'H'], 'name': 'LDrr'}},
 {'code': 101,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '65',
  'instruction': 'LD H, L',
  'name': 'LDrr_hl',
  'templateData': {'args': ['H', 'L'], 'name': 'LDrr'}},
 {'code': 102,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '66',
  'instruction': 'LD H, [HL]',
  'name': 'LDrHLm_h',
  'templateData': {'args': ['H'], 'name': 'LDrHLm_'}},
 {'code': 103,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '67',
  'instruction': 'LD H, A',
  'name': 'LDrr_ha',
  'templateData': {'args': ['H', 'A'], 'name': 'LDrr'}},
 {'code': 104,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '68',
  'instruction': 'LD L, B',
  'name': 'LDrr_lb',
  'templateData': {'args': ['L', 'B'], 'name': 'LDrr'}},
 {'code': 105,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '69',
  'instruction': 'LD L, C',
  'name': 'LDrr_lc',
  'templateData': {'args': ['L', 'C'], 'name': 'LDrr'}},
 {'code': 106,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6A',
  'instruction': 'LD L, D',
  'name': 'LDrr_ld',
  'templateData': {'args': ['L', 'D'], 'name': 'LDrr'}},
 {'code': 107,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6B',
  'instruction': 'LD L, E',
  'name': 'LDrr_le',
  'templateData': {'args': ['L', 'E'], 'name': 'LDrr'}},
 {'code': 108,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6C',
  'instruction': 'LD L, H',
  'name': 'LDrr_lh',
  'templateData': {'args': ['L', 'H'], 'name': 'LDrr'}},
 {'code': 109,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6D',
  'instruction': 'LD L, L',
  'name': 'LDrr_ll',
  'templateData': {'args': ['L', 'L'], 'name': 'LDrr'}},
 {'code': 110,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6E',
  'instruction': 'LD L, [HL]',
  'name': 'LDrHLm_l',
  'templateData': {'args': ['L'], 'name': 'LDrHLm_'}},
 {'code': 111,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '6F',
  'instruction': 'LD L, A',
  'name': 'LDrr_la',
  'templateData': {'args': ['L', 'A'], 'name': 'LDrr'}},
 {'code': 112,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '70',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_b',
  'templateData': {'args': ['B'], 'name': 'LDHLmr_'}},
 {'code': 113,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '71',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_c',
  'templateData': {'args': ['C'], 'name': 'LDHLmr_'}},
 {'code': 114,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '72',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_d',
  'templateData': {'args': ['D'], 'name': 'LDHLmr_'}},
 {'code': 115,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '73',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_e',
  'templateData': {'args': ['E'], 'name': 'LDHLmr_'}},
 {'code': 116,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '74',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_h',
  'templateData': {'args': ['H'], 'name': 'LDHLmr_'}},
 {'code': 117,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '75',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_l',
  'templateData': {'args': ['L'], 'name': 'LDHLmr_'}},
 {'code': 118,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '76',
  'instruction': 'HALT',
  'name': 'HALT',
  'templateData': {'args': [''], 'name': 'HALT'}},
 {'code': 119,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '77',
  'instruction': 'LD [HL], X',
  'name': 'LDHLmr_a',
  'templateData': {'args': ['A'], 'name': 'LDHLmr_'}},
 {'code': 120,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '78',
  'instruction': 'LD A, B',
  'name': 'LDrr_ab',
  'templateData': {'args': ['A', 'B'], 'name': 'LDrr'}},
 {'code': 121,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '79',
  'instruction': 'LD A, C',
  'name': 'LDrr_ac',
  'templateData': {'args': ['A', 'C'], 'name': 'LDrr'}},
 {'code': 122,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7A',
  'instruction': 'LD A, D',
  'name': 'LDrr_ad',
  'templateData': {'args': ['A', 'D'], 'name': 'LDrr'}},
 {'code': 123,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7B',
  'instruction': 'LD A, E',
  'name': 'LDrr_ae',
  'templateData': {'args': ['A', 'E'], 'name': 'LDrr'}},
 {'code': 124,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7C',
  'instruction': 'LD A, H',
  'name': 'LDrr_ah',
  'templateData': {'args': ['A', 'H'], 'name': 'LDrr'}},
 {'code': 125,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7D',
  'instruction': 'LD A, L',
  'name': 'LDrr_al',
  'templateData': {'args': ['A', 'L'], 'name': 'LDrr'}},
 {'code': 126,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7E',
  'instruction': 'LD A, [HL]',
  'name': 'LDrHLm_a',
  'templateData': {'args': ['A'], 'name': 'LDrHLm_'}},
 {'code': 127,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '7F',
  'instruction': 'LD A, A',
  'name': 'LDrr_aa',
  'templateData': {'args': ['A', 'A'], 'name': 'LDrr'}},
 {'code': 128,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '80',
  'instruction': 'ADD A, B',
  'name': 'ADDr_b',
  'templateData': {'args': ['B'], 'name': 'ADDr'}},
 {'code': 129,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '81',
  'instruction': 'ADD A, C',
  'name': 'ADDr_c',
  'templateData': {'args': ['C'], 'name': 'ADDr'}},
 {'code': 130,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '82',
  'instruction': 'ADD A, D',
  'name': 'ADDr_d',
  'templateData': {'args': ['D'], 'name': 'ADDr'}},
 {'code': 131,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '83',
  'instruction': 'ADD A, E',
  'name': 'ADDr_e',
  'templateData': {'args': ['E'], 'name': 'ADDr'}},
 {'code': 132,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '84',
  'instruction': 'ADD A, H',
  'name': 'ADDr_h',
  'templateData': {'args': ['H'], 'name': 'ADDr'}},
 {'code': 133,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '85',
  'instruction': 'ADD A, L',
  'name': 'ADDr_l',
  'templateData': {'args': ['L'], 'name': 'ADDr'}},
 {'code': 134,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '86',
  'instruction': 'ADD A, [HL]',
  'name': 'ADDHL',
  'templateData': {'args': [''], 'name': 'ADDHL'}},
 {'code': 135,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '87',
  'instruction': 'ADD A, A',
  'name': 'ADDr_a',
  'templateData': {'args': ['A'], 'name': 'ADDr'}},
 {'code': 136,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '88',
  'instruction': 'ADC A, B',
  'name': 'ADCr_b',
  'templateData': {'args': ['B'], 'name': 'ADCr'}},
 {'code': 137,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '89',
  'instruction': 'ADC A, C',
  'name': 'ADCr_c',
  'templateData': {'args': ['C'], 'name': 'ADCr'}},
 {'code': 138,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8A',
  'instruction': 'ADC A, D',
  'name': 'ADCr_d',
  'templateData': {'args': ['D'], 'name': 'ADCr'}},
 {'code': 139,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8B',
  'instruction': 'ADC A, E',
  'name': 'ADCr_e',
  'templateData': {'args': ['E'], 'name': 'ADCr'}},
 {'code': 140,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8C',
  'instruction': 'ADC A, H',
  'name': 'ADCr_h',
  'templateData': {'args': ['H'], 'name': 'ADCr'}},
 {'code': 141,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8D',
  'instruction': 'ADC A, L',
  'name': 'ADCr_l',
  'templateData': {'args': ['L'], 'name': 'ADCr'}},
 {'code': 142,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8E',
  'instruction': 'ADC A, [HL]',
  'name': 'ADCHL',
  'templateData': {'args': [''], 'name': 'ADCHL'}},
 {'code': 143,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': '8F',
  'instruction': 'ADC A, A',
  'name': 'ADCr_a',
  'templateData': {'args': ['A'], 'name': 'ADCr'}},
 {'code': 144,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '90',
  'instruction': 'SUB A, B',
  'name': 'SUBr_b',
  'templateData': {'args': ['B'], 'name': 'SUBr'}},
 {'code': 145,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '91',
  'instruction': 'SUB A, C',
  'name': 'SUBr_c',
  'templateData': {'args': ['C'], 'name': 'SUBr'}},
 {'code': 146,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '92',
  'instruction': 'SUB A, D',
  'name': 'SUBr_d',
  'templateData': {'args': ['D'], 'name': 'SUBr'}},
 {'code': 147,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '93',
  'instruction': 'SUB A, E',
  'name': 'SUBr_e',
  'templateData': {'args': ['E'], 'name': 'SUBr'}},
 {'code': 148,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '94',
  'instruction': 'SUB A, H',
  'name': 'SUBr_h',
  'templateData': {'args': ['H'], 'name': 'SUBr'}},
 {'code': 149,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '95',
  'instruction': 'SUB A, L',
  'name': 'SUBr_l',
  'templateData': {'args': ['L'], 'name': 'SUBr'}},
 {'code': 150,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '96',
  'instruction': 'SUB A, [HL]',
  'name': 'SUBHL',
  'templateData': {'args': [''], 'name': 'SUBHL'}},
 {'code': 151,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '97',
  'instruction': 'SUB A, A',
  'name': 'SUBr_a',
  'templateData': {'args': ['A'], 'name': 'SUBr'}},
 {'code': 152,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '98',
  'instruction': 'SBC A, B',
  'name': 'SBCr_b',
  'templateData': {'args': ['B'], 'name': 'SBCr'}},
 {'code': 153,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '99',
  'instruction': 'SBC A, C',
  'name': 'SBCr_c',
  'templateData': {'args': ['C'], 'name': 'SBCr'}},
 {'code': 154,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9A',
  'instruction': 'SBC A, D',
  'name': 'SBCr_d',
  'templateData': {'args': ['D'], 'name': 'SBCr'}},
 {'code': 155,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9B',
  'instruction': 'SBC A, E',
  'name': 'SBCr_e',
  'templateData': {'args': ['E'], 'name': 'SBCr'}},
 {'code': 156,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9C',
  'instruction': 'SBC A, H',
  'name': 'SBCr_h',
  'templateData': {'args': ['H'], 'name': 'SBCr'}},
 {'code': 157,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9D',
  'instruction': 'SBC A, L',
  'name': 'SBCr_l',
  'templateData': {'args': ['L'], 'name': 'SBCr'}},
 {'code': 158,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9E',
  'instruction': 'SBC A, [HL]',
  'name': 'SBCHL',
  'templateData': {'args': [''], 'name': 'SBCHL'}},
 {'code': 159,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': '9F',
  'instruction': 'SBC A, A',
  'name': 'SBCr_a',
  'templateData': {'args': ['A'], 'name': 'SBCr'}},
 {'code': 160,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A0',
  'instruction': 'AND A, B',
  'name': 'ANDr_b',
  'templateData': {'args': ['B'], 'name': 'ANDr'}},
 {'code': 161,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A1',
  'instruction': 'AND A, C',
  'name': 'ANDr_c',
  'templateData': {'args': ['C'], 'name': 'ANDr'}},
 {'code': 162,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A2',
  'instruction': 'AND A, D',
  'name': 'ANDr_d',
  'templateData': {'args': ['D'], 'name': 'ANDr'}},
 {'code': 163,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A3',
  'instruction': 'AND A, E',
  'name': 'ANDr_e',
  'templateData': {'args': ['E'], 'name': 'ANDr'}},
 {'code': 164,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A4',
  'instruction': 'AND A, H',
  'name': 'ANDr_h',
  'templateData': {'args': ['H'], 'name': 'ANDr'}},
 {'code': 165,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A5',
  'instruction': 'AND A, L',
  'name': 'ANDr_l',
  'templateData': {'args': ['L'], 'name': 'ANDr'}},
 {'code': 166,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A6',
  'instruction': 'AND A, [HL]',
  'name': 'ANDHL',
  'templateData': {'args': [''], 'name': 'ANDHL'}},
 {'code': 167,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A7',
  'instruction': 'AND A, A',
  'name': 'ANDr_a',
  'templateData': {'args': ['A'], 'name': 'ANDr'}},
 {'code': 168,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A8',
  'instruction': 'XOR A, B',
  'name': 'XORr_b',
  'templateData': {'args': ['B'], 'name': 'XORr'}},
 {'code': 169,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'A9',
  'instruction': 'XOR A, C',
  'name': 'XORr_c',
  'templateData': {'args': ['C'], 'name': 'XORr'}},
 {'code': 170,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AA',
  'instruction': 'XOR A, D',
  'name': 'XORr_d',
  'templateData': {'args': ['D'], 'name': 'XORr'}},
 {'code': 171,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AB',
  'instruction': 'XOR A, E',
  'name': 'XORr_e',
  'templateData': {'args': ['E'], 'name': 'XORr'}},
 {'code': 172,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AC',
  'instruction': 'XOR A, H',
  'name': 'XORr_h',
  'templateData': {'args': ['H'], 'name': 'XORr'}},
 {'code': 173,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AD',
  'instruction': 'XOR A, L',
  'name': 'XORr_l',
  'templateData': {'args': ['L'], 'name': 'XORr'}},
 {'code': 174,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AE',
  'instruction': 'XOR A, [HL]',
  'name': 'XORHL',
  'templateData': {'args': [''], 'name': 'XORHL'}},
 {'code': 175,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'AF',
  'instruction': 'XOR A, A',
  'name': 'XORr_a',
  'templateData': {'args': ['A'], 'name': 'XORr'}},
 {'code': 176,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B0',
  'instruction': 'OR A, B',
  'name': 'ORr_b',
  'templateData': {'args': ['B'], 'name': 'ORr'}},
 {'code': 177,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B1',
  'instruction': 'OR A, C',
  'name': 'ORr_c',
  'templateData': {'args': ['C'], 'name': 'ORr'}},
 {'code': 178,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B2',
  'instruction': 'OR A, D',
  'name': 'ORr_d',
  'templateData': {'args': ['D'], 'name': 'ORr'}},
 {'code': 179,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B3',
  'instruction': 'OR A, E',
  'name': 'ORr_e',
  'templateData': {'args': ['E'], 'name': 'ORr'}},
 {'code': 180,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B4',
  'instruction': 'OR A, H',
  'name': 'ORr_h',
  'templateData': {'args': ['H'], 'name': 'ORr'}},
 {'code': 181,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B5',
  'instruction': 'OR A, L',
  'name': 'ORr_l',
  'templateData': {'args': ['L'], 'name': 'ORr'}},
 {'code': 182,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B6',
  'instruction': 'OR A, [HL]',
  'name': 'ORHL',
  'templateData': {'args': [''], 'name': 'ORHL'}},
 {'code': 183,
  'cycles': 4,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'B7',
  'instruction': 'OR A, A',
  'name': 'ORr_a',
  'templateData': {'args': ['A'], 'name': 'ORr'}},
 {'code': 184,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'B8',
  'instruction': 'CP A, B',
  'name': 'CPr_b',
  'templateData': {'args': ['B'], 'name': 'CPr'}},
 {'code': 185,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'B9',
  'instruction': 'CP A, C',
  'name': 'CPr_c',
  'templateData': {'args': ['C'], 'name': 'CPr'}},
 {'code': 186,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BA',
  'instruction': 'CP A, D',
  'name': 'CPr_d',
  'templateData': {'args': ['D'], 'name': 'CPr'}},
 {'code': 187,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BB',
  'instruction': 'CP A, E',
  'name': 'CPr_e',
  'templateData': {'args': ['E'], 'name': 'CPr'}},
 {'code': 188,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BC',
  'instruction': 'CP A, H',
  'name': 'CPr_h',
  'templateData': {'args': ['H'], 'name': 'CPr'}},
 {'code': 189,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BD',
  'instruction': 'CP A, L',
  'name': 'CPr_l',
  'templateData': {'args': ['L'], 'name': 'CPr'}},
 {'code': 190,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BE',
  'instruction': 'CP A, [HL]',
  'name': 'CPHL',
  'templateData': {'args': [''], 'name': 'CPHL'}},
 {'code': 191,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'BF',
  'instruction': 'CP A, A',
  'name': 'CPr_a',
  'templateData': {'args': ['A'], 'name': 'CPr'}},
 {'code': 192,
  'cycles': [20, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C0',
  'instruction': 'RET NZ',
  'name': 'RETNZ',
  'templateData': {'args': [''], 'name': 'RETNZ'}},
 {'code': 193,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C1',
  'instruction': 'POP BC',
  'name': 'POPBC',
  'templateData': {'args': ['B', 'C'], 'name': 'POP'}},
 {'code': 194,
  'cycles': [16, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C2',
  'instruction': 'JP NZ, a16',
  'name': 'JPNZnn',
  'templateData': {'args': [''], 'name': 'JPNZnn'}},
 {'code': 195,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C3',
  'instruction': 'JP a16',
  'name': 'JPnn',
  'templateData': {'args': [''], 'name': 'JPnn'}},
 {'code': 196,
  'cycles': [24, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C4',
  'instruction': 'CALL NZ,a16',
  'name': 'CALLNZnn',
  'templateData': {'args': [''], 'name': 'CALLNZnn'}},
 {'code': 197,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C5',
  'instruction': 'PUSH BC',
  'name': 'PUSHBC',
  'templateData': {'args': ['B', 'C'], 'name': 'PUSH'}},
 {'code': 198,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': 'C6',
  'instruction': 'ADD A, d8',
  'name': 'ADDn',
  'templateData': {'args': [''], 'name': 'ADDn'}},
 {'code': 199,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C7',
  'instruction': 'RST 00H',
  'name': 'RST00',
  'templateData': {'args': ['0x00'], 'name': 'RSTXX'}},
 {'code': 200,
  'cycles': [20, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C8',
  'instruction': 'RET Z',
  'name': 'RETZ',
  'templateData': {'args': [''], 'name': 'RETZ'}},
 {'code': 201,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C9',
  'instruction': 'RET',
  'name': 'RET',
  'templateData': {'args': [''], 'name': 'RET'}},
 {'code': 202,
  'cycles': [16, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CA',
  'instruction': 'JP Z,a16',
  'name': 'JPZnn',
  'templateData': {'args': [''], 'name': 'JPZnn'}},
 {'code': 203,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CB',
  'instruction': 'PREFIX CB',
  'name': 'MAPcb',
  'templateData': {'args': [''], 'name': 'CBCall'}},
 {'code': 204,
  'cycles': [24, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CC',
  'instruction': 'CALL Z,a16',
  'name': 'CALLZnn',
  'templateData': {'args': [''], 'name': 'CALLZnn'}},
 {'code': 205,
  'cycles': 24,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CD',
  'instruction': 'CALL a16',
  'name': 'CALLnn',
  'templateData': {'args': [''], 'name': 'CALLnn'}},
 {'code': 206,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': False, 'zero': 'Z'},
  'hexCode': 'CE',
  'instruction': 'ADC A, d8',
  'name': 'ADCn',
  'templateData': {'args': [''], 'name': 'ADCn'}},
 {'code': 207,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CF',
  'instruction': 'RST 08H',
  'name': 'RST08',
  'templateData': {'args': ['0x08'], 'name': 'RSTXX'}},
 {'code': 208,
  'cycles': [20, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D0',
  'instruction': 'RET NC',
  'name': 'RETNC',
  'templateData': {'args': [''], 'name': 'RETNC'}},
 {'code': 209,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D1',
  'instruction': 'POP DE',
  'name': 'POPDE',
  'templateData': {'args': ['D', 'E'], 'name': 'POP'}},
 {'code': 210,
  'cycles': [16, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D2',
  'instruction': 'JP NC,a16',
  'name': 'JPNCnn',
  'templateData': {'args': [''], 'name': 'JPNCnn'}},
 {'code': 211,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D3',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xD3'], 'name': 'NOPWARN'}},
 {'code': 212,
  'cycles': [24, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D4',
  'instruction': 'CALL NC, a16',
  'name': 'CALLNCnn',
  'templateData': {'args': [''], 'name': 'CALLNCnn'}},
 {'code': 213,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D5',
  'instruction': 'PUSH DE',
  'name': 'PUSHDE',
  'templateData': {'args': ['D', 'E'], 'name': 'PUSH'}},
 {'code': 214,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'D6',
  'instruction': 'SUB A, d8',
  'name': 'SUBn',
  'templateData': {'args': [''], 'name': 'SUBn'}},
 {'code': 215,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D7',
  'instruction': 'RST 10H',
  'name': 'RST10',
  'templateData': {'args': ['0x10'], 'name': 'RSTXX'}},
 {'code': 216,
  'cycles': [20, 8],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D8',
  'instruction': 'RET C',
  'name': 'RETC',
  'templateData': {'args': [''], 'name': 'RETC'}},
 {'code': 217,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D9',
  'instruction': 'RETI',
  'name': 'RETI',
  'templateData': {'args': [''], 'name': 'RETI'}},
 {'code': 218,
  'cycles': [16, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DA',
  'instruction': 'JP C, a16',
  'name': 'JPCnn',
  'templateData': {'args': [''], 'name': 'JPCnn'}},
 {'code': 219,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DB',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xDB'], 'name': 'NOPWARN'}},
 {'code': 220,
  'cycles': [24, 12],
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DC',
  'instruction': 'CALL C, a16',
  'name': 'CALLCnn',
  'templateData': {'args': [''], 'name': 'CALLCnn'}},
 {'code': 221,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DD',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xDD'], 'name': 'NOPWARN'}},
 {'code': 222,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'DE',
  'instruction': 'SBC A, d8',
  'name': 'SBCn',
  'templateData': {'args': [''], 'name': 'SBCn'}},
 {'code': 223,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DF',
  'instruction': 'RST 18H',
  'name': 'RST18',
  'templateData': {'args': ['0x18'], 'name': 'RSTXX'}},
 {'code': 224,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E0',
  'instruction': 'LD [$FF00+a8], A',
  'name': 'LDIOnA',
  'templateData': {'args': [''], 'name': 'LDIOnA'}},
 {'code': 225,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E1',
  'instruction': 'POP HL',
  'name': 'POPHL',
  'templateData': {'args': ['H', 'L'], 'name': 'POP'}},
 {'code': 226,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E2',
  'instruction': 'LD [$FF00+C], A',
  'name': 'LDIOCA',
  'templateData': {'args': [''], 'name': 'LDIOCA'}},
 {'code': 227,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E3',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xE3'], 'name': 'NOPWARN'}},
 {'code': 228,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E4',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xE4'], 'name': 'NOPWARN'}},
 {'code': 229,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E5',
  'instruction': 'PUSH HL',
  'name': 'PUSHHL',
  'templateData': {'args': ['H', 'L'], 'name': 'PUSH'}},
 {'code': 230,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': True,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'E6',
  'instruction': 'AND A, d8',
  'name': 'ANDn',
  'templateData': {'args': [''], 'name': 'ANDn'}},
 {'code': 231,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E7',
  'instruction': 'RST 20H',
  'name': 'RST20',
  'templateData': {'args': ['0x20'], 'name': 'RSTXX'}},
 {'code': 232,
  'cycles': 16,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': False},
  'hexCode': 'E8',
  'instruction': 'ADD SP, r8',
  'name': 'ADDSPn',
  'templateData': {'args': [''], 'name': 'ADDSPn'}},
 {'code': 233,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E9',
  'instruction': 'JP [HL]',
  'name': 'JPHL',
  'templateData': {'args': [''], 'name': 'JPHL'}},
 {'code': 234,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EA',
  'instruction': 'LD [a16], A',
  'name': 'LDmmA',
  'templateData': {'args': ['A'], 'name': 'LDmm_'}},
 {'code': 235,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EB',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xEB'], 'name': 'NOPWARN'}},
 {'code': 236,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EC',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xEC'], 'name': 'NOPWARN'}},
 {'code': 237,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'ED',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xED'], 'name': 'NOPWARN'}},
 {'code': 238,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'EE',
  'instruction': 'XOR A, d8',
  'name': 'XORn',
  'templateData': {'args': [''], 'name': 'XORn'}},
 {'code': 239,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EF',
  'instruction': 'RST 28H',
  'name': 'RST28',
  'templateData': {'args': ['0x28'], 'name': 'RSTXX'}},
 {'code': 240,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F0',
  'instruction': 'LD A, [$FF00+a8]',
  'name': 'LDAIOn',
  'templateData': {'args': [''], 'name': 'LDAIOn'}},
 {'code': 241,
  'cycles': 12,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': 'Z'},
  'hexCode': 'F1',
  'instruction': 'POP AF',
  'name': 'POPAF',
  'templateData': {'args': ['A', 'F'], 'name': 'POP'}},
 {'code': 242,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F2',
  'instruction': 'LD A, [$FF00+C]',
  'name': 'LDAIOC',
  'templateData': {'args': [''], 'name': 'LDAIOC'}},
 {'code': 243,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F3',
  'instruction': 'DI',
  'name': 'DI',
  'templateData': {'args': [''], 'name': 'DI'}},
 {'code': 244,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F4',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xF4'], 'name': 'NOPWARN'}},
 {'code': 245,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F5',
  'instruction': 'PUSH AF',
  'name': 'PUSHAF',
  'templateData': {'args': ['A', 'F'], 'name': 'PUSH'}},
 {'code': 246,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': 'F6',
  'instruction': 'OR A, d8',
  'name': 'ORn',
  'templateData': {'args': [''], 'name': 'ORn'}},
 {'code': 247,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F7',
  'instruction': 'RST 30H',
  'name': 'RST30',
  'templateData': {'args': ['0x30'], 'name': 'RSTXX'}},
 {'code': 248,
  'cycles': 12,
  'flagResult': {'carry': None,
                 'halfcarry': None,
                 'sub': False,
                 'zero': False},
  'hexCode': 'F8',
  'instruction': 'LD HL, SP+r8',
  'name': 'LDHLSPn',
  'templateData': {'args': [''], 'name': 'LDHLSPn'}},
 {'code': 249,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F9',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': [''], 'name': 'LDHLSPr'}},
 {'code': 250,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FA',
  'instruction': 'LD A, [a16]',
  'name': 'LDAmm',
  'templateData': {'args': ['A'], 'name': 'LD_mm'}},
 {'code': 251,
  'cycles': 4,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FB',
  'instruction': 'EI',
  'name': 'EI',
  'templateData': {'args': [''], 'name': 'EI'}},
 {'code': 252,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FC',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xFC'], 'name': 'NOPWARN'}},
 {'code': 253,
  'cycles': 0,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FD',
  'instruction': 'UNDEFINED',
  'name': 'XX',
  'templateData': {'args': ['0xFD'], 'name': 'NOPWARN'}},
 {'code': 254,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': True, 'zero': 'Z'},
  'hexCode': 'FE',
  'instruction': 'CP A, d8',
  'name': 'CPn',
  'templateData': {'args': [''], 'name': 'CPn'}},
 {'code': 255,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FF',
  'instruction': 'RST 38H',
  'name': 'RST38',
  'templateData': {'args': ['0x38'], 'name': 'RSTXX'}}]
