#!/usr/bin/env python

# AUTO GENERATED FILE - PLEASE CHECK gen.py! #

InstructionsCB = [{'code': 0,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '00',
  'instruction': 'RLC B',
  'name': 'RLCr_b',
  'templateData': {'args': ['B'], 'name': 'RLCr'}},
 {'code': 1,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '01',
  'instruction': 'RLC C',
  'name': 'RLCr_c',
  'templateData': {'args': ['C'], 'name': 'RLCr'}},
 {'code': 2,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '02',
  'instruction': 'RLC D',
  'name': 'RLCr_d',
  'templateData': {'args': ['D'], 'name': 'RLCr'}},
 {'code': 3,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '03',
  'instruction': 'RLC E',
  'name': 'RLCr_e',
  'templateData': {'args': ['E'], 'name': 'RLCr'}},
 {'code': 4,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '04',
  'instruction': 'RLC H',
  'name': 'RLCr_h',
  'templateData': {'args': ['H'], 'name': 'RLCr'}},
 {'code': 5,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '05',
  'instruction': 'RLC L',
  'name': 'RLCr_l',
  'templateData': {'args': ['L'], 'name': 'RLCr'}},
 {'code': 6,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '06',
  'instruction': 'RLC [HL]',
  'name': 'RLCHL',
  'templateData': {'args': [''], 'name': 'RLCHL'}},
 {'code': 7,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '07',
  'instruction': 'RLC A',
  'name': 'RLCr_a',
  'templateData': {'args': ['A'], 'name': 'RLCr'}},
 {'code': 8,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '08',
  'instruction': 'RRC B',
  'name': 'RRCr_b',
  'templateData': {'args': ['B'], 'name': 'RRCr'}},
 {'code': 9,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '09',
  'instruction': 'RRC C',
  'name': 'RRCr_c',
  'templateData': {'args': ['C'], 'name': 'RRCr'}},
 {'code': 10,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0A',
  'instruction': 'RRC D',
  'name': 'RRCr_d',
  'templateData': {'args': ['D'], 'name': 'RRCr'}},
 {'code': 11,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0B',
  'instruction': 'RRC E',
  'name': 'RRCr_e',
  'templateData': {'args': ['E'], 'name': 'RRCr'}},
 {'code': 12,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0C',
  'instruction': 'RRC H',
  'name': 'RRCr_h',
  'templateData': {'args': ['H'], 'name': 'RRCr'}},
 {'code': 13,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0D',
  'instruction': 'RRC L',
  'name': 'RRCr_l',
  'templateData': {'args': ['L'], 'name': 'RRCr'}},
 {'code': 14,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0E',
  'instruction': 'RRC [HL]',
  'name': 'RRCHL',
  'templateData': {'args': [''], 'name': 'RRCHL'}},
 {'code': 15,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '0F',
  'instruction': 'RRC A',
  'name': 'RRCr_a',
  'templateData': {'args': ['A'], 'name': 'RRCr'}},
 {'code': 16,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '10',
  'instruction': 'RL B',
  'name': 'RLr_b',
  'templateData': {'args': ['B'], 'name': 'RLr'}},
 {'code': 17,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '11',
  'instruction': 'RL C',
  'name': 'RLr_c',
  'templateData': {'args': ['C'], 'name': 'RLr'}},
 {'code': 18,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '12',
  'instruction': 'RL D',
  'name': 'RLr_d',
  'templateData': {'args': ['D'], 'name': 'RLr'}},
 {'code': 19,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '13',
  'instruction': 'RL E',
  'name': 'RLr_e',
  'templateData': {'args': ['E'], 'name': 'RLr'}},
 {'code': 20,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '14',
  'instruction': 'RL H',
  'name': 'RLr_h',
  'templateData': {'args': ['H'], 'name': 'RLr'}},
 {'code': 21,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '15',
  'instruction': 'RL L',
  'name': 'RLr_l',
  'templateData': {'args': ['L'], 'name': 'RLr'}},
 {'code': 22,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '16',
  'instruction': 'RL [HL]',
  'name': 'RLHL',
  'templateData': {'args': [''], 'name': 'RLHL'}},
 {'code': 23,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '17',
  'instruction': 'RL X',
  'name': 'RLr_a',
  'templateData': {'args': ['A'], 'name': 'RLr'}},
 {'code': 24,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '18',
  'instruction': 'RR B',
  'name': 'RRr_b',
  'templateData': {'args': ['B'], 'name': 'RRr'}},
 {'code': 25,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '19',
  'instruction': 'RR C',
  'name': 'RRr_c',
  'templateData': {'args': ['C'], 'name': 'RRr'}},
 {'code': 26,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1A',
  'instruction': 'RR D',
  'name': 'RRr_d',
  'templateData': {'args': ['D'], 'name': 'RRr'}},
 {'code': 27,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1B',
  'instruction': 'RR E',
  'name': 'RRr_e',
  'templateData': {'args': ['E'], 'name': 'RRr'}},
 {'code': 28,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1C',
  'instruction': 'RR H',
  'name': 'RRr_h',
  'templateData': {'args': ['H'], 'name': 'RRr'}},
 {'code': 29,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1D',
  'instruction': 'RR L',
  'name': 'RRr_l',
  'templateData': {'args': ['L'], 'name': 'RRr'}},
 {'code': 30,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1E',
  'instruction': 'RR [HL]',
  'name': 'RRHL',
  'templateData': {'args': [''], 'name': 'RRHL'}},
 {'code': 31,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '1F',
  'instruction': 'RR A',
  'name': 'RRr_a',
  'templateData': {'args': ['A'], 'name': 'RRr'}},
 {'code': 32,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '20',
  'instruction': 'SLA B',
  'name': 'SLAr_b',
  'templateData': {'args': ['B'], 'name': 'SLAr'}},
 {'code': 33,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '21',
  'instruction': 'SLA C',
  'name': 'SLAr_c',
  'templateData': {'args': ['C'], 'name': 'SLAr'}},
 {'code': 34,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '22',
  'instruction': 'SLA D',
  'name': 'SLAr_d',
  'templateData': {'args': ['D'], 'name': 'SLAr'}},
 {'code': 35,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '23',
  'instruction': 'SLA E',
  'name': 'SLAr_e',
  'templateData': {'args': ['E'], 'name': 'SLAr'}},
 {'code': 36,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '24',
  'instruction': 'SLA H',
  'name': 'SLAr_h',
  'templateData': {'args': ['H'], 'name': 'SLAr'}},
 {'code': 37,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '25',
  'instruction': 'SLA L',
  'name': 'SLAr_l',
  'templateData': {'args': ['L'], 'name': 'SLAr'}},
 {'code': 38,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '26',
  'instruction': 'SLA [HL]',
  'name': 'SLAHL',
  'templateData': {'args': [''], 'name': 'SLAHL'}},
 {'code': 39,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '27',
  'instruction': 'SLA A',
  'name': 'SLAr_a',
  'templateData': {'args': ['A'], 'name': 'SLAr'}},
 {'code': 40,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '28',
  'instruction': 'SRA B',
  'name': 'SRAr_b',
  'templateData': {'args': ['B'], 'name': 'SRAr'}},
 {'code': 41,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '29',
  'instruction': 'SRA C',
  'name': 'SRAr_c',
  'templateData': {'args': ['C'], 'name': 'SRAr'}},
 {'code': 42,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2A',
  'instruction': 'SRA D',
  'name': 'SRAr_d',
  'templateData': {'args': ['D'], 'name': 'SRAr'}},
 {'code': 43,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2B',
  'instruction': 'SRA E',
  'name': 'SRAr_e',
  'templateData': {'args': ['E'], 'name': 'SRAr'}},
 {'code': 44,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2C',
  'instruction': 'SRA H',
  'name': 'SRAr_h',
  'templateData': {'args': ['H'], 'name': 'SRAr'}},
 {'code': 45,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2D',
  'instruction': 'SRA L',
  'name': 'SRAr_l',
  'templateData': {'args': ['L'], 'name': 'SRAr'}},
 {'code': 46,
  'cycles': 16,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2E',
  'instruction': 'SRA [HL]',
  'name': 'SRAHL',
  'templateData': {'args': [''], 'name': 'SRAHL'}},
 {'code': 47,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '2F',
  'instruction': 'SRA A',
  'name': 'SRAr_a',
  'templateData': {'args': ['A'], 'name': 'SRAr'}},
 {'code': 48,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '30',
  'instruction': 'SWAP B',
  'name': 'SWAPr_b',
  'templateData': {'args': ['B'], 'name': 'SWAPr'}},
 {'code': 49,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '31',
  'instruction': 'SWAP C',
  'name': 'SWAPr_c',
  'templateData': {'args': ['C'], 'name': 'SWAPr'}},
 {'code': 50,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '32',
  'instruction': 'SWAP D',
  'name': 'SWAPr_d',
  'templateData': {'args': ['D'], 'name': 'SWAPr'}},
 {'code': 51,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '33',
  'instruction': 'SWAP E',
  'name': 'SWAPr_e',
  'templateData': {'args': ['E'], 'name': 'SWAPr'}},
 {'code': 52,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '34',
  'instruction': 'SWAP H',
  'name': 'SWAPr_h',
  'templateData': {'args': ['H'], 'name': 'SWAPr'}},
 {'code': 53,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '35',
  'instruction': 'SWAP L',
  'name': 'SWAPr_l',
  'templateData': {'args': ['L'], 'name': 'SWAPr'}},
 {'code': 54,
  'cycles': 16,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '36',
  'instruction': 'SWAP [HL]',
  'name': 'SWAPHL',
  'templateData': {'args': [''], 'name': 'SWAPHL'}},
 {'code': 55,
  'cycles': 8,
  'flagResult': {'carry': False,
                 'halfcarry': False,
                 'sub': False,
                 'zero': 'Z'},
  'hexCode': '37',
  'instruction': 'SWAP A',
  'name': 'SWAPr_a',
  'templateData': {'args': ['A'], 'name': 'SWAPr'}},
 {'code': 56,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '38',
  'instruction': 'SRL B',
  'name': 'SRLr_b',
  'templateData': {'args': ['B'], 'name': 'SRLr'}},
 {'code': 57,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '39',
  'instruction': 'SRL C',
  'name': 'SRLr_c',
  'templateData': {'args': ['C'], 'name': 'SRLr'}},
 {'code': 58,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3A',
  'instruction': 'SRL D',
  'name': 'SRLr_d',
  'templateData': {'args': ['D'], 'name': 'SRLr'}},
 {'code': 59,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3B',
  'instruction': 'SRL E',
  'name': 'SRLr_e',
  'templateData': {'args': ['E'], 'name': 'SRLr'}},
 {'code': 60,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3C',
  'instruction': 'SRL H',
  'name': 'SRLr_h',
  'templateData': {'args': ['H'], 'name': 'SRLr'}},
 {'code': 61,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3D',
  'instruction': 'SRL L',
  'name': 'SRLr_l',
  'templateData': {'args': ['L'], 'name': 'SRLr'}},
 {'code': 62,
  'cycles': 16,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3E',
  'instruction': 'SRL [HL]',
  'name': 'SRLHL',
  'templateData': {'args': [''], 'name': 'SRLHL'}},
 {'code': 63,
  'cycles': 8,
  'flagResult': {'carry': 'C', 'halfcarry': False, 'sub': False, 'zero': 'Z'},
  'hexCode': '3F',
  'instruction': 'SRL A',
  'name': 'SRLr_a',
  'templateData': {'args': ['A'], 'name': 'SRLr'}},
 {'code': 64,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '40',
  'instruction': 'BIT 0, B',
  'name': 'BIT0b',
  'templateData': {'args': ['0', 'B'], 'name': 'BIT'}},
 {'code': 65,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '41',
  'instruction': 'BIT 0, C',
  'name': 'BIT0c',
  'templateData': {'args': ['0', 'C'], 'name': 'BIT'}},
 {'code': 66,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '42',
  'instruction': 'BIT 0, D',
  'name': 'BIT0d',
  'templateData': {'args': ['0', 'D'], 'name': 'BIT'}},
 {'code': 67,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '43',
  'instruction': 'BIT 0, E',
  'name': 'BIT0e',
  'templateData': {'args': ['0', 'E'], 'name': 'BIT'}},
 {'code': 68,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '44',
  'instruction': 'BIT 0, H',
  'name': 'BIT0h',
  'templateData': {'args': ['0', 'H'], 'name': 'BIT'}},
 {'code': 69,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '45',
  'instruction': 'BIT 0, L',
  'name': 'BIT0l',
  'templateData': {'args': ['0', 'L'], 'name': 'BIT'}},
 {'code': 70,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '46',
  'instruction': 'BIT 0, [HL]',
  'name': 'BIT0m',
  'templateData': {'args': ['0'], 'name': 'BITm'}},
 {'code': 71,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '47',
  'instruction': 'BIT 0, A',
  'name': 'BIT0a',
  'templateData': {'args': ['0', 'A'], 'name': 'BIT'}},
 {'code': 72,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '48',
  'instruction': 'BIT 1, B',
  'name': 'BIT1b',
  'templateData': {'args': ['1', 'B'], 'name': 'BIT'}},
 {'code': 73,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '49',
  'instruction': 'BIT 1, C',
  'name': 'BIT1c',
  'templateData': {'args': ['1', 'C'], 'name': 'BIT'}},
 {'code': 74,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4A',
  'instruction': 'BIT 1, D',
  'name': 'BIT1d',
  'templateData': {'args': ['1', 'D'], 'name': 'BIT'}},
 {'code': 75,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4B',
  'instruction': 'BIT 1, E',
  'name': 'BIT1e',
  'templateData': {'args': ['1', 'E'], 'name': 'BIT'}},
 {'code': 76,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4C',
  'instruction': 'BIT 1, H',
  'name': 'BIT1h',
  'templateData': {'args': ['1', 'H'], 'name': 'BIT'}},
 {'code': 77,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4D',
  'instruction': 'BIT 1, L',
  'name': 'BIT1l',
  'templateData': {'args': ['1', 'L'], 'name': 'BIT'}},
 {'code': 78,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4E',
  'instruction': 'BIT 1, [HL]',
  'name': 'BIT1m',
  'templateData': {'args': ['1'], 'name': 'BITm'}},
 {'code': 79,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '4F',
  'instruction': 'BIT 1, A',
  'name': 'BIT1a',
  'templateData': {'args': ['1', 'A'], 'name': 'BIT'}},
 {'code': 80,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '50',
  'instruction': 'BIT 2, B',
  'name': 'BIT2b',
  'templateData': {'args': ['2', 'B'], 'name': 'BIT'}},
 {'code': 81,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '51',
  'instruction': 'BIT 2, C',
  'name': 'BIT2c',
  'templateData': {'args': ['2', 'C'], 'name': 'BIT'}},
 {'code': 82,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '52',
  'instruction': 'BIT 2, D',
  'name': 'BIT2d',
  'templateData': {'args': ['2', 'D'], 'name': 'BIT'}},
 {'code': 83,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '53',
  'instruction': 'BIT 2, E',
  'name': 'BIT2e',
  'templateData': {'args': ['2', 'E'], 'name': 'BIT'}},
 {'code': 84,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '54',
  'instruction': 'BIT 2, H',
  'name': 'BIT2h',
  'templateData': {'args': ['2', 'H'], 'name': 'BIT'}},
 {'code': 85,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '55',
  'instruction': 'BIT 2, L',
  'name': 'BIT2l',
  'templateData': {'args': ['2', 'L'], 'name': 'BIT'}},
 {'code': 86,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '56',
  'instruction': 'BIT 2, [HL]',
  'name': 'BIT2m',
  'templateData': {'args': ['2'], 'name': 'BITm'}},
 {'code': 87,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '57',
  'instruction': 'BIT 2, A',
  'name': 'BIT2a',
  'templateData': {'args': ['2', 'A'], 'name': 'BIT'}},
 {'code': 88,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '58',
  'instruction': 'BIT 3, B',
  'name': 'BIT3b',
  'templateData': {'args': ['3', 'B'], 'name': 'BIT'}},
 {'code': 89,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '59',
  'instruction': 'BIT 3, C',
  'name': 'BIT3c',
  'templateData': {'args': ['3', 'C'], 'name': 'BIT'}},
 {'code': 90,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5A',
  'instruction': 'BIT 3, D',
  'name': 'BIT3d',
  'templateData': {'args': ['3', 'D'], 'name': 'BIT'}},
 {'code': 91,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5B',
  'instruction': 'BIT 3, E',
  'name': 'BIT3e',
  'templateData': {'args': ['3', 'E'], 'name': 'BIT'}},
 {'code': 92,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5C',
  'instruction': 'BIT 3, H',
  'name': 'BIT3h',
  'templateData': {'args': ['3', 'H'], 'name': 'BIT'}},
 {'code': 93,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5D',
  'instruction': 'BIT 3, L',
  'name': 'BIT3l',
  'templateData': {'args': ['3', 'L'], 'name': 'BIT'}},
 {'code': 94,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5E',
  'instruction': 'BIT 3, [HL]',
  'name': 'BIT3m',
  'templateData': {'args': ['3'], 'name': 'BITm'}},
 {'code': 95,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '5F',
  'instruction': 'BIT 3, A',
  'name': 'BIT3a',
  'templateData': {'args': ['3', 'A'], 'name': 'BIT'}},
 {'code': 96,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '60',
  'instruction': 'BIT 4, B',
  'name': 'BIT4b',
  'templateData': {'args': ['4', 'B'], 'name': 'BIT'}},
 {'code': 97,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '61',
  'instruction': 'BIT 4, C',
  'name': 'BIT4c',
  'templateData': {'args': ['4', 'C'], 'name': 'BIT'}},
 {'code': 98,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '62',
  'instruction': 'BIT 4, D',
  'name': 'BIT4d',
  'templateData': {'args': ['4', 'D'], 'name': 'BIT'}},
 {'code': 99,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '63',
  'instruction': 'BIT 4, E',
  'name': 'BIT4e',
  'templateData': {'args': ['4', 'E'], 'name': 'BIT'}},
 {'code': 100,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '64',
  'instruction': 'BIT 4, H',
  'name': 'BIT4h',
  'templateData': {'args': ['4', 'H'], 'name': 'BIT'}},
 {'code': 101,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '65',
  'instruction': 'BIT 4, L',
  'name': 'BIT4l',
  'templateData': {'args': ['4', 'L'], 'name': 'BIT'}},
 {'code': 102,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '66',
  'instruction': 'BIT 4, [HL]',
  'name': 'BIT4m',
  'templateData': {'args': ['4'], 'name': 'BITm'}},
 {'code': 103,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '67',
  'instruction': 'BIT 4, A',
  'name': 'BIT4a',
  'templateData': {'args': ['4', 'A'], 'name': 'BIT'}},
 {'code': 104,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '68',
  'instruction': 'BIT 5, B',
  'name': 'BIT5b',
  'templateData': {'args': ['5', 'B'], 'name': 'BIT'}},
 {'code': 105,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '69',
  'instruction': 'BIT 5, C',
  'name': 'BIT5c',
  'templateData': {'args': ['5', 'C'], 'name': 'BIT'}},
 {'code': 106,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6A',
  'instruction': 'BIT 5, D',
  'name': 'BIT5d',
  'templateData': {'args': ['5', 'D'], 'name': 'BIT'}},
 {'code': 107,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6B',
  'instruction': 'BIT 5, E',
  'name': 'BIT5e',
  'templateData': {'args': ['5', 'E'], 'name': 'BIT'}},
 {'code': 108,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6C',
  'instruction': 'BIT 5, H',
  'name': 'BIT5h',
  'templateData': {'args': ['5', 'H'], 'name': 'BIT'}},
 {'code': 109,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6D',
  'instruction': 'BIT 5, L',
  'name': 'BIT5l',
  'templateData': {'args': ['5', 'L'], 'name': 'BIT'}},
 {'code': 110,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6E',
  'instruction': 'BIT 5, [HL]',
  'name': 'BIT5m',
  'templateData': {'args': ['5'], 'name': 'BITm'}},
 {'code': 111,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '6F',
  'instruction': 'BIT 5, A',
  'name': 'BIT5a',
  'templateData': {'args': ['5', 'A'], 'name': 'BIT'}},
 {'code': 112,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '70',
  'instruction': 'BIT 6, B',
  'name': 'BIT6b',
  'templateData': {'args': ['6', 'B'], 'name': 'BIT'}},
 {'code': 113,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '71',
  'instruction': 'BIT 6, C',
  'name': 'BIT6c',
  'templateData': {'args': ['6', 'C'], 'name': 'BIT'}},
 {'code': 114,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '72',
  'instruction': 'BIT 6, D',
  'name': 'BIT6d',
  'templateData': {'args': ['6', 'D'], 'name': 'BIT'}},
 {'code': 115,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '73',
  'instruction': 'BIT 6, E',
  'name': 'BIT6e',
  'templateData': {'args': ['6', 'E'], 'name': 'BIT'}},
 {'code': 116,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '74',
  'instruction': 'BIT 6, H',
  'name': 'BIT6h',
  'templateData': {'args': ['6', 'H'], 'name': 'BIT'}},
 {'code': 117,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '75',
  'instruction': 'BIT 6, L',
  'name': 'BIT6l',
  'templateData': {'args': ['6', 'L'], 'name': 'BIT'}},
 {'code': 118,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '76',
  'instruction': 'BIT 6, [HL]',
  'name': 'BIT6m',
  'templateData': {'args': ['6'], 'name': 'BITm'}},
 {'code': 119,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '77',
  'instruction': 'BIT 6, A',
  'name': 'BIT6a',
  'templateData': {'args': ['6', 'A'], 'name': 'BIT'}},
 {'code': 120,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '78',
  'instruction': 'BIT 7, B',
  'name': 'BIT7b',
  'templateData': {'args': ['7', 'B'], 'name': 'BIT'}},
 {'code': 121,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '79',
  'instruction': 'BIT 7, C',
  'name': 'BIT7c',
  'templateData': {'args': ['7', 'C'], 'name': 'BIT'}},
 {'code': 122,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7A',
  'instruction': 'BIT 7, D',
  'name': 'BIT7d',
  'templateData': {'args': ['7', 'D'], 'name': 'BIT'}},
 {'code': 123,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7B',
  'instruction': 'BIT 7, E',
  'name': 'BIT7e',
  'templateData': {'args': ['7', 'E'], 'name': 'BIT'}},
 {'code': 124,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7C',
  'instruction': 'BIT 7, H',
  'name': 'BIT7h',
  'templateData': {'args': ['7', 'H'], 'name': 'BIT'}},
 {'code': 125,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7D',
  'instruction': 'BIT 7, L',
  'name': 'BIT7l',
  'templateData': {'args': ['7', 'L'], 'name': 'BIT'}},
 {'code': 126,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7E',
  'instruction': 'BIT 7, [HL]',
  'name': 'BIT7m',
  'templateData': {'args': ['7'], 'name': 'BITm'}},
 {'code': 127,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': True, 'sub': False, 'zero': 'Z'},
  'hexCode': '7F',
  'instruction': 'BIT 7, A',
  'name': 'BIT7a',
  'templateData': {'args': ['7', 'A'], 'name': 'BIT'}},
 {'code': 128,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '80',
  'instruction': 'RES 0, B',
  'name': 'RES0b',
  'templateData': {'args': ['0', 'B'], 'name': 'RES'}},
 {'code': 129,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '81',
  'instruction': 'RES 0, C',
  'name': 'RES0c',
  'templateData': {'args': ['0', 'C'], 'name': 'RES'}},
 {'code': 130,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '82',
  'instruction': 'RES 0, D',
  'name': 'RES0d',
  'templateData': {'args': ['0', 'D'], 'name': 'RES'}},
 {'code': 131,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '83',
  'instruction': 'RES 0, E',
  'name': 'RES0e',
  'templateData': {'args': ['0', 'E'], 'name': 'RES'}},
 {'code': 132,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '84',
  'instruction': 'RES 0, H',
  'name': 'RES0h',
  'templateData': {'args': ['0', 'H'], 'name': 'RES'}},
 {'code': 133,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '85',
  'instruction': 'RES 0, L',
  'name': 'RES0l',
  'templateData': {'args': ['0', 'L'], 'name': 'RES'}},
 {'code': 134,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '86',
  'instruction': 'RES 0, [HL]',
  'name': 'RES0m',
  'templateData': {'args': ['0'], 'name': 'RESHL'}},
 {'code': 135,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '87',
  'instruction': 'RES 0, A',
  'name': 'RES0a',
  'templateData': {'args': ['0', 'A'], 'name': 'RES'}},
 {'code': 136,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '88',
  'instruction': 'RES 1, B',
  'name': 'RES1b',
  'templateData': {'args': ['1', 'B'], 'name': 'RES'}},
 {'code': 137,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '89',
  'instruction': 'RES 1, C',
  'name': 'RES1c',
  'templateData': {'args': ['1', 'C'], 'name': 'RES'}},
 {'code': 138,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8A',
  'instruction': 'RES 1, D',
  'name': 'RES1d',
  'templateData': {'args': ['1', 'D'], 'name': 'RES'}},
 {'code': 139,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8B',
  'instruction': 'RES 1, E',
  'name': 'RES1e',
  'templateData': {'args': ['1', 'E'], 'name': 'RES'}},
 {'code': 140,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8C',
  'instruction': 'RES 1, H',
  'name': 'RES1h',
  'templateData': {'args': ['1', 'H'], 'name': 'RES'}},
 {'code': 141,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8D',
  'instruction': 'RES 1, L',
  'name': 'RES1l',
  'templateData': {'args': ['1', 'L'], 'name': 'RES'}},
 {'code': 142,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8E',
  'instruction': 'RES 1, [HL]',
  'name': 'RES1m',
  'templateData': {'args': ['1'], 'name': 'RESHL'}},
 {'code': 143,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '8F',
  'instruction': 'RES 1, A',
  'name': 'RES1a',
  'templateData': {'args': ['1', 'A'], 'name': 'RES'}},
 {'code': 144,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '90',
  'instruction': 'RES 2, B',
  'name': 'RES2b',
  'templateData': {'args': ['2', 'B'], 'name': 'RES'}},
 {'code': 145,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '91',
  'instruction': 'RES 2, C',
  'name': 'RES2c',
  'templateData': {'args': ['2', 'C'], 'name': 'RES'}},
 {'code': 146,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '92',
  'instruction': 'RES 2, D',
  'name': 'RES2d',
  'templateData': {'args': ['2', 'D'], 'name': 'RES'}},
 {'code': 147,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '93',
  'instruction': 'RES 2, E',
  'name': 'RES2e',
  'templateData': {'args': ['2', 'E'], 'name': 'RES'}},
 {'code': 148,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '94',
  'instruction': 'RES 2, H',
  'name': 'RES2h',
  'templateData': {'args': ['2', 'H'], 'name': 'RES'}},
 {'code': 149,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '95',
  'instruction': 'RES 2, L',
  'name': 'RES2l',
  'templateData': {'args': ['2', 'L'], 'name': 'RES'}},
 {'code': 150,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '96',
  'instruction': 'RES 2, [HL]',
  'name': 'RES2m',
  'templateData': {'args': ['2'], 'name': 'RESHL'}},
 {'code': 151,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '97',
  'instruction': 'RES 2, A',
  'name': 'RES2a',
  'templateData': {'args': ['2', 'A'], 'name': 'RES'}},
 {'code': 152,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '98',
  'instruction': 'RES 3, B',
  'name': 'RES3b',
  'templateData': {'args': ['3', 'B'], 'name': 'RES'}},
 {'code': 153,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '99',
  'instruction': 'RES 3, C',
  'name': 'RES3c',
  'templateData': {'args': ['3', 'C'], 'name': 'RES'}},
 {'code': 154,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9A',
  'instruction': 'RES 3, D',
  'name': 'RES3d',
  'templateData': {'args': ['3', 'D'], 'name': 'RES'}},
 {'code': 155,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9B',
  'instruction': 'RES 3, E',
  'name': 'RES3e',
  'templateData': {'args': ['3', 'E'], 'name': 'RES'}},
 {'code': 156,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9C',
  'instruction': 'RES 3, H',
  'name': 'RES3h',
  'templateData': {'args': ['3', 'H'], 'name': 'RES'}},
 {'code': 157,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9D',
  'instruction': 'RES 3, L',
  'name': 'RES3l',
  'templateData': {'args': ['3', 'L'], 'name': 'RES'}},
 {'code': 158,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9E',
  'instruction': 'RES 3, [HL]',
  'name': 'RES3m',
  'templateData': {'args': ['3'], 'name': 'RESHL'}},
 {'code': 159,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': '9F',
  'instruction': 'RES 3, A',
  'name': 'RES3a',
  'templateData': {'args': ['3', 'A'], 'name': 'RES'}},
 {'code': 160,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A0',
  'instruction': 'RES 4, B',
  'name': 'RES4b',
  'templateData': {'args': ['4', 'B'], 'name': 'RES'}},
 {'code': 161,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A1',
  'instruction': 'RES 4, C',
  'name': 'RES4c',
  'templateData': {'args': ['4', 'C'], 'name': 'RES'}},
 {'code': 162,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A2',
  'instruction': 'RES 4, D',
  'name': 'RES4d',
  'templateData': {'args': ['4', 'D'], 'name': 'RES'}},
 {'code': 163,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A3',
  'instruction': 'RES 4, E',
  'name': 'RES4e',
  'templateData': {'args': ['4', 'E'], 'name': 'RES'}},
 {'code': 164,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A4',
  'instruction': 'RES 4, H',
  'name': 'RES4h',
  'templateData': {'args': ['4', 'H'], 'name': 'RES'}},
 {'code': 165,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A5',
  'instruction': 'RES 4, L',
  'name': 'RES4l',
  'templateData': {'args': ['4', 'L'], 'name': 'RES'}},
 {'code': 166,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A6',
  'instruction': 'RES 4, [HL]',
  'name': 'RES4m',
  'templateData': {'args': ['4'], 'name': 'RESHL'}},
 {'code': 167,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A7',
  'instruction': 'RES 4, A',
  'name': 'RES4a',
  'templateData': {'args': ['4', 'A'], 'name': 'RES'}},
 {'code': 168,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A8',
  'instruction': 'RES 5, B',
  'name': 'RES5b',
  'templateData': {'args': ['6', 'B'], 'name': 'RES'}},
 {'code': 169,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'A9',
  'instruction': 'RES 5, C',
  'name': 'RES5c',
  'templateData': {'args': ['6', 'C'], 'name': 'RES'}},
 {'code': 170,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AA',
  'instruction': 'RES 5, D',
  'name': 'RES5d',
  'templateData': {'args': ['6', 'D'], 'name': 'RES'}},
 {'code': 171,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AB',
  'instruction': 'RES 5, E',
  'name': 'RES5e',
  'templateData': {'args': ['6', 'E'], 'name': 'RES'}},
 {'code': 172,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AC',
  'instruction': 'RES 5, H',
  'name': 'RES5h',
  'templateData': {'args': ['6', 'H'], 'name': 'RES'}},
 {'code': 173,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AD',
  'instruction': 'RES 5, L',
  'name': 'RES5l',
  'templateData': {'args': ['6', 'L'], 'name': 'RES'}},
 {'code': 174,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AE',
  'instruction': 'RES 5, [HL]',
  'name': 'RES5m',
  'templateData': {'args': ['6'], 'name': 'RESHL'}},
 {'code': 175,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'AF',
  'instruction': 'RES 5, A',
  'name': 'RES5a',
  'templateData': {'args': ['6', 'A'], 'name': 'RES'}},
 {'code': 176,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B0',
  'instruction': 'RES 6, B',
  'name': 'RES6b',
  'templateData': {'args': ['6', 'B'], 'name': 'RES'}},
 {'code': 177,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B1',
  'instruction': 'RES 6, C',
  'name': 'RES6c',
  'templateData': {'args': ['6', 'C'], 'name': 'RES'}},
 {'code': 178,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B2',
  'instruction': 'RES 6, D',
  'name': 'RES6d',
  'templateData': {'args': ['6', 'D'], 'name': 'RES'}},
 {'code': 179,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B3',
  'instruction': 'RES 6, E',
  'name': 'RES6e',
  'templateData': {'args': ['6', 'E'], 'name': 'RES'}},
 {'code': 180,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B4',
  'instruction': 'RES 6, H',
  'name': 'RES6h',
  'templateData': {'args': ['6', 'H'], 'name': 'RES'}},
 {'code': 181,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B5',
  'instruction': 'RES 6, L',
  'name': 'RES6l',
  'templateData': {'args': ['6', 'L'], 'name': 'RES'}},
 {'code': 182,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B6',
  'instruction': 'RES 6, [HL]',
  'name': 'RES6m',
  'templateData': {'args': ['6'], 'name': 'RESHL'}},
 {'code': 183,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B7',
  'instruction': 'RES 6, A',
  'name': 'RES6a',
  'templateData': {'args': ['6', 'A'], 'name': 'RES'}},
 {'code': 184,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B8',
  'instruction': 'RES 7, B',
  'name': 'RES7b',
  'templateData': {'args': ['7', 'B'], 'name': 'RES'}},
 {'code': 185,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'B9',
  'instruction': 'RES 7, C',
  'name': 'RES7c',
  'templateData': {'args': ['7', 'C'], 'name': 'RES'}},
 {'code': 186,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BA',
  'instruction': 'RES 7, D',
  'name': 'RES7d',
  'templateData': {'args': ['7', 'D'], 'name': 'RES'}},
 {'code': 187,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BB',
  'instruction': 'RES 7, E',
  'name': 'RES7e',
  'templateData': {'args': ['7', 'E'], 'name': 'RES'}},
 {'code': 188,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BC',
  'instruction': 'RES 7, H',
  'name': 'RES7h',
  'templateData': {'args': ['7', 'H'], 'name': 'RES'}},
 {'code': 189,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BD',
  'instruction': 'RES 7, L',
  'name': 'RES7l',
  'templateData': {'args': ['7', 'L'], 'name': 'RES'}},
 {'code': 190,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BE',
  'instruction': 'RES 7, [HL]',
  'name': 'RES7m',
  'templateData': {'args': ['7'], 'name': 'RESHL'}},
 {'code': 191,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'BF',
  'instruction': 'RES 7, A',
  'name': 'RES7a',
  'templateData': {'args': ['7', 'A'], 'name': 'RES'}},
 {'code': 192,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C0',
  'instruction': 'SET 0, B',
  'name': 'SET0b',
  'templateData': {'args': ['0', 'B'], 'name': 'SET'}},
 {'code': 193,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C1',
  'instruction': 'SET 0, C',
  'name': 'SET0c',
  'templateData': {'args': ['0', 'C'], 'name': 'SET'}},
 {'code': 194,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C2',
  'instruction': 'SET 0, D',
  'name': 'SET0d',
  'templateData': {'args': ['0', 'D'], 'name': 'SET'}},
 {'code': 195,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C3',
  'instruction': 'SET 0, E',
  'name': 'SET0e',
  'templateData': {'args': ['0', 'E'], 'name': 'SET'}},
 {'code': 196,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C4',
  'instruction': 'SET 0, H',
  'name': 'SET0h',
  'templateData': {'args': ['0', 'H'], 'name': 'SET'}},
 {'code': 197,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C5',
  'instruction': 'SET 0, L',
  'name': 'SET0l',
  'templateData': {'args': ['0', 'L'], 'name': 'SET'}},
 {'code': 198,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C6',
  'instruction': 'SET 0, [HL]',
  'name': 'SET0m',
  'templateData': {'args': ['0'], 'name': 'SETHL'}},
 {'code': 199,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C7',
  'instruction': 'SET 0, A',
  'name': 'SET0a',
  'templateData': {'args': ['0', 'A'], 'name': 'SET'}},
 {'code': 200,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C8',
  'instruction': 'SET 1, B',
  'name': 'SET1b',
  'templateData': {'args': ['1', 'B'], 'name': 'SET'}},
 {'code': 201,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'C9',
  'instruction': 'SET 1, C',
  'name': 'SET1c',
  'templateData': {'args': ['1', 'C'], 'name': 'SET'}},
 {'code': 202,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CA',
  'instruction': 'SET 1, D',
  'name': 'SET1d',
  'templateData': {'args': ['1', 'D'], 'name': 'SET'}},
 {'code': 203,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CB',
  'instruction': 'SET 1, E',
  'name': 'SET1e',
  'templateData': {'args': ['1', 'E'], 'name': 'SET'}},
 {'code': 204,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CC',
  'instruction': 'SET 1, H',
  'name': 'SET1h',
  'templateData': {'args': ['1', 'H'], 'name': 'SET'}},
 {'code': 205,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CD',
  'instruction': 'SET 1, L',
  'name': 'SET1l',
  'templateData': {'args': ['1', 'L'], 'name': 'SET'}},
 {'code': 206,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CE',
  'instruction': 'SET 1, [HL]',
  'name': 'SET1m',
  'templateData': {'args': ['1'], 'name': 'SETHL'}},
 {'code': 207,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'CF',
  'instruction': 'SET 1, A',
  'name': 'SET1a',
  'templateData': {'args': ['1', 'A'], 'name': 'SET'}},
 {'code': 208,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D0',
  'instruction': 'SET 2, B',
  'name': 'SET2b',
  'templateData': {'args': ['2', 'B'], 'name': 'SET'}},
 {'code': 209,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D1',
  'instruction': 'SET 2, C',
  'name': 'SET2c',
  'templateData': {'args': ['2', 'C'], 'name': 'SET'}},
 {'code': 210,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D2',
  'instruction': 'SET 2, D',
  'name': 'SET2d',
  'templateData': {'args': ['2', 'D'], 'name': 'SET'}},
 {'code': 211,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D3',
  'instruction': 'SET 2, E',
  'name': 'SET2e',
  'templateData': {'args': ['2', 'E'], 'name': 'SET'}},
 {'code': 212,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D4',
  'instruction': 'SET 2, H',
  'name': 'SET2h',
  'templateData': {'args': ['2', 'H'], 'name': 'SET'}},
 {'code': 213,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D5',
  'instruction': 'SET 2, L',
  'name': 'SET2l',
  'templateData': {'args': ['2', 'L'], 'name': 'SET'}},
 {'code': 214,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D6',
  'instruction': 'SET 2, [HL]',
  'name': 'SET2m',
  'templateData': {'args': ['2'], 'name': 'SETHL'}},
 {'code': 215,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D7',
  'instruction': 'SET 2, A',
  'name': 'SET2a',
  'templateData': {'args': ['2', 'A'], 'name': 'SET'}},
 {'code': 216,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D8',
  'instruction': 'SET 3, B',
  'name': 'SET3b',
  'templateData': {'args': ['3', 'B'], 'name': 'SET'}},
 {'code': 217,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'D9',
  'instruction': 'SET 3, C',
  'name': 'SET3c',
  'templateData': {'args': ['3', 'C'], 'name': 'SET'}},
 {'code': 218,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DA',
  'instruction': 'SET 3, D',
  'name': 'SET3d',
  'templateData': {'args': ['3', 'D'], 'name': 'SET'}},
 {'code': 219,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DB',
  'instruction': 'SET 3, E',
  'name': 'SET3e',
  'templateData': {'args': ['3', 'E'], 'name': 'SET'}},
 {'code': 220,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DC',
  'instruction': 'SET 3, H',
  'name': 'SET3h',
  'templateData': {'args': ['3', 'H'], 'name': 'SET'}},
 {'code': 221,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DD',
  'instruction': 'SET 3, L',
  'name': 'SET3l',
  'templateData': {'args': ['3', 'L'], 'name': 'SET'}},
 {'code': 222,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DE',
  'instruction': 'SET 3, [HL]',
  'name': 'SET3m',
  'templateData': {'args': ['3'], 'name': 'SETHL'}},
 {'code': 223,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'DF',
  'instruction': 'SET 3, A',
  'name': 'SET3a',
  'templateData': {'args': ['3', 'A'], 'name': 'SET'}},
 {'code': 224,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E0',
  'instruction': 'SET 4, B',
  'name': 'SET4b',
  'templateData': {'args': ['4', 'B'], 'name': 'SET'}},
 {'code': 225,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E1',
  'instruction': 'SET 4, C',
  'name': 'SET4c',
  'templateData': {'args': ['4', 'C'], 'name': 'SET'}},
 {'code': 226,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E2',
  'instruction': 'SET 4, D',
  'name': 'SET4d',
  'templateData': {'args': ['4', 'D'], 'name': 'SET'}},
 {'code': 227,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E3',
  'instruction': 'SET 4, E',
  'name': 'SET4e',
  'templateData': {'args': ['4', 'E'], 'name': 'SET'}},
 {'code': 228,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E4',
  'instruction': 'SET 4, H',
  'name': 'SET4h',
  'templateData': {'args': ['4', 'H'], 'name': 'SET'}},
 {'code': 229,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E5',
  'instruction': 'SET 4, L',
  'name': 'SET4l',
  'templateData': {'args': ['4', 'L'], 'name': 'SET'}},
 {'code': 230,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E6',
  'instruction': 'SET 4, [HL]',
  'name': 'SET4m',
  'templateData': {'args': ['4'], 'name': 'SETHL'}},
 {'code': 231,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E7',
  'instruction': 'SET 4, A',
  'name': 'SET4a',
  'templateData': {'args': ['4', 'A'], 'name': 'SET'}},
 {'code': 232,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E8',
  'instruction': 'SET 5, B',
  'name': 'SET5b',
  'templateData': {'args': ['5', 'B'], 'name': 'SET'}},
 {'code': 233,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'E9',
  'instruction': 'SET 5, C',
  'name': 'SET5c',
  'templateData': {'args': ['5', 'C'], 'name': 'SET'}},
 {'code': 234,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EA',
  'instruction': 'SET 5, D',
  'name': 'SET5d',
  'templateData': {'args': ['5', 'D'], 'name': 'SET'}},
 {'code': 235,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EB',
  'instruction': 'SET 5, E',
  'name': 'SET5e',
  'templateData': {'args': ['5', 'E'], 'name': 'SET'}},
 {'code': 236,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EC',
  'instruction': 'SET 5, H',
  'name': 'SET5h',
  'templateData': {'args': ['5', 'H'], 'name': 'SET'}},
 {'code': 237,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'ED',
  'instruction': 'SET 5, L',
  'name': 'SET5l',
  'templateData': {'args': ['5', 'L'], 'name': 'SET'}},
 {'code': 238,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EE',
  'instruction': 'SET 5, [HL]',
  'name': 'SET5m',
  'templateData': {'args': ['5'], 'name': 'SETHL'}},
 {'code': 239,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'EF',
  'instruction': 'SET 5, A',
  'name': 'SET5a',
  'templateData': {'args': ['5', 'A'], 'name': 'SET'}},
 {'code': 240,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F0',
  'instruction': 'SET 6, B',
  'name': 'SET6b',
  'templateData': {'args': ['6', 'B'], 'name': 'SET'}},
 {'code': 241,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F1',
  'instruction': 'SET 6, C',
  'name': 'SET6c',
  'templateData': {'args': ['6', 'C'], 'name': 'SET'}},
 {'code': 242,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F2',
  'instruction': 'SET 6, D',
  'name': 'SET6d',
  'templateData': {'args': ['6', 'D'], 'name': 'SET'}},
 {'code': 243,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F3',
  'instruction': 'SET 6, E',
  'name': 'SET6e',
  'templateData': {'args': ['6', 'E'], 'name': 'SET'}},
 {'code': 244,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F4',
  'instruction': 'SET 6, H',
  'name': 'SET6h',
  'templateData': {'args': ['6', 'H'], 'name': 'SET'}},
 {'code': 245,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F5',
  'instruction': 'SET 6, L',
  'name': 'SET6l',
  'templateData': {'args': ['6', 'L'], 'name': 'SET'}},
 {'code': 246,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F6',
  'instruction': 'SET 6, [HL]',
  'name': 'SET6m',
  'templateData': {'args': ['6'], 'name': 'SETHL'}},
 {'code': 247,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F7',
  'instruction': 'SET 6, A',
  'name': 'SET6a',
  'templateData': {'args': ['6', 'A'], 'name': 'SET'}},
 {'code': 248,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F8',
  'instruction': 'SET 7, B',
  'name': 'SET7b',
  'templateData': {'args': ['7', 'B'], 'name': 'SET'}},
 {'code': 249,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'F9',
  'instruction': 'SET 7, C',
  'name': 'SET7c',
  'templateData': {'args': ['7', 'C'], 'name': 'SET'}},
 {'code': 250,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FA',
  'instruction': 'SET 7, D',
  'name': 'SET7d',
  'templateData': {'args': ['7', 'D'], 'name': 'SET'}},
 {'code': 251,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FB',
  'instruction': 'SET 7, E',
  'name': 'SET7e',
  'templateData': {'args': ['7', 'E'], 'name': 'SET'}},
 {'code': 252,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FC',
  'instruction': 'SET 7, H',
  'name': 'SET7h',
  'templateData': {'args': ['7', 'H'], 'name': 'SET'}},
 {'code': 253,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FD',
  'instruction': 'SET 7, L',
  'name': 'SET7l',
  'templateData': {'args': ['7', 'L'], 'name': 'SET'}},
 {'code': 254,
  'cycles': 16,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FE',
  'instruction': 'SET 7, [HL]',
  'name': 'SET7m',
  'templateData': {'args': ['7'], 'name': 'SETHL'}},
 {'code': 255,
  'cycles': 8,
  'flagResult': {'carry': None, 'halfcarry': None, 'sub': None, 'zero': None},
  'hexCode': 'FF',
  'instruction': 'SET 7, A',
  'name': 'SET7a',
  'templateData': {'args': ['7', 'A'], 'name': 'SET'}}]
